# Example
version: "3"

services:
  sarcophilus:
    build: .
    network_mode: host
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./bluetooth:/var/lib/bluetooth
    environment:
      SINK_DEVICE: "front:CARD=RD88,DEV=0"